#!/usr/bin/env python3
# Run a ceasar cipher on stdin

def caesar_cipher_decrypt(ciphertext, shift):
    decrypted_text = ""
    for char in ciphertext:

        if not char.isalpha():
            decrypted_text += char
            break

        if char.isupper():
            decrypted_text += chr((ord(char) - shift - 65) % 26 + 65)
        else:
            decrypted_text += chr((ord(char) - shift - 97) % 26 + 97)

    return decrypted_text

def brute_force_caesar_cipher(ciphertext):
    for shift in range(26):
        decrypted_text = caesar_cipher_decrypt(ciphertext, shift)
        print(f"Shift {str(shift).zfill(2)}: {decrypted_text}")

ciphertext = input()

brute_force_caesar_cipher(ciphertext)

