#!/usr/bin/env python3
# Calculate your GPA based on your grades and credits. 'S' here is shorthand for an 'A+'

grades = {
    "S": 10,
    "A": 9,
    "B": 8,
    "C": 7,
    "D": 6,
    "E": 5,
    "F": 0,
}

dist = {
    "MATHS":    ["A", 4],
    "BE":       ["B", 3],
    "PHY":      ["B", 3],
    "BME":      ["C", 3],
    "MOS":      ["A", 3],
    "ENG":      ["S", 2],
    "WORKSHOP": ["A", 1],
    "PHY LAB":  ["A", 1],
    "EG":       ["A", 1],
    "UHV":      ["A", 1],
}

# dist = {
#     "MATHS":    ["S", 6],
#     "BET":      ["S", 3],
#     "CHM":      ["A", 3],
#     "PSUC":     ["S", 3],
#     "BIO":      ["A", 3],
#     "EVS":      ["S", 2],
#     "PSUC LAB": ["S", 1],
#     "CHM LAB":  ["A", 1],
#     "EG":       ["A", 1],
#     "HRC":      ["S", 1],
# }

def calc_gpa(distribution: dict):
    total_credits = sum(value[1] for value in distribution.values())
    grade_points = 0

    for subject in distribution.keys():
        grade = distribution[subject][0]
        grade_points += grades[grade] * distribution[subject][1]

    print(round(grade_points / total_credits, 2))

calc_gpa(dist)

